"""
Investigation collaboration — assignment, review requests, and tracking.

When an investigation needs a second opinion, escalation review, or
inter-team handoff, the collaboration layer records the assignment and
dispatches the appropriate notifications. All collaboration activity
is tenant-scoped and audit-trailed.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any

log = logging.getLogger("evidentrx.saas.notifications.collaboration")


class AssignmentStatus(str, Enum):
    OPEN       = "open"
    ACCEPTED   = "accepted"
    IN_REVIEW  = "in_review"
    COMPLETED  = "completed"
    DECLINED   = "declined"
    REASSIGNED = "reassigned"


class ReviewOutcome(str, Enum):
    CONCUR        = "concur"         # reviewer agrees with original finding
    DISAGREE      = "disagree"       # reviewer disputes; must escalate
    NEEDS_MORE    = "needs_more"     # more evidence required
    ESCALATE      = "escalate"       # forward to senior analyst / legal
    CLOSE_FP      = "close_fp"       # reviewer calls false positive
    CLOSE_TP      = "close_tp"       # reviewer confirms true positive


@dataclass
class InvestigationAssignment:
    """
    An assignment of an investigation to an analyst or team.

    Tracks the full handoff chain: assigned_by → assignee, with optional
    org scoping and deadline enforcement.
    """
    assignment_id:   str
    tenant_id:       str
    investigation_id: str
    assigned_by:     str          # user_id of assigner
    assignee_id:     str          # user_id of recipient
    org_id:          str | None
    status:          AssignmentStatus = AssignmentStatus.OPEN
    notes:           str              = ""
    due_at:          datetime | None = None
    assigned_at:     datetime     = field(default_factory=lambda: datetime.now(tz=UTC))
    accepted_at:     datetime | None = None
    completed_at:    datetime | None = None
    prior_assignment_id: str | None = None   # chain for reassignments

    @property
    def is_overdue(self) -> bool:
        if self.due_at is None or self.status in (
            AssignmentStatus.COMPLETED,
            AssignmentStatus.DECLINED,
        ):
            return False
        return datetime.now(tz=UTC) > self.due_at

    def to_dict(self) -> dict[str, Any]:
        return {
            "assignment_id":    self.assignment_id,
            "tenant_id":        self.tenant_id,
            "investigation_id": self.investigation_id,
            "assigned_by":      self.assigned_by,
            "assignee_id":      self.assignee_id,
            "org_id":           self.org_id,
            "status":           self.status.value,
            "notes":            self.notes,
            "due_at":           self.due_at.isoformat() if self.due_at else None,
            "assigned_at":      self.assigned_at.isoformat(),
            "is_overdue":       self.is_overdue,
        }


@dataclass
class ReviewRequest:
    """
    A formal request for peer or senior review of an investigation finding.

    ReviewRequests are generated by analysts who want a second opinion
    before closing or escalating. A reviewer's decision is recorded as
    a ReviewOutcome and feeds back into the investigation workflow.
    """
    review_id:        str
    tenant_id:        str
    investigation_id: str
    requested_by:     str
    reviewer_id:      str
    reason:           str
    status:           AssignmentStatus = AssignmentStatus.OPEN
    outcome:          ReviewOutcome | None  = None
    outcome_notes:    str                      = ""
    requested_at:     datetime   = field(default_factory=lambda: datetime.now(tz=UTC))
    completed_at:     datetime | None       = None
    priority:         str        = "normal"    # "normal" | "urgent"

    def to_dict(self) -> dict[str, Any]:
        return {
            "review_id":        self.review_id,
            "tenant_id":        self.tenant_id,
            "investigation_id": self.investigation_id,
            "requested_by":     self.requested_by,
            "reviewer_id":      self.reviewer_id,
            "reason":           self.reason,
            "status":           self.status.value,
            "outcome":          self.outcome.value if self.outcome else None,
            "outcome_notes":    self.outcome_notes,
            "requested_at":     self.requested_at.isoformat(),
            "completed_at":     self.completed_at.isoformat() if self.completed_at else None,
            "priority":         self.priority,
        }


class CollaborationTracker:
    """
    Central tracker for investigation assignments and review requests.

    Does not dispatch notifications directly — callers are expected to
    pass a NotificationDispatcher and call send_* after state changes.
    """

    def __init__(self) -> None:
        self._assignments: dict[str, InvestigationAssignment] = {}
        self._reviews:     dict[str, ReviewRequest]           = {}
        # (investigation_id, tenant_id) → [assignment_id, ...]
        self._by_investigation: dict[tuple[str, str], list[str]] = {}

    # ── Assignments ────────────────────────────────────────────────────────────

    def assign(
        self,
        tenant_id:        str,
        investigation_id: str,
        assigned_by:      str,
        assignee_id:      str,
        org_id:           str | None  = None,
        notes:            str            = "",
        due_at:           datetime | None = None,
    ) -> InvestigationAssignment:
        """Assign an investigation to an analyst."""
        assignment = InvestigationAssignment(
            assignment_id    = str(uuid.uuid4()),
            tenant_id        = tenant_id,
            investigation_id = investigation_id,
            assigned_by      = assigned_by,
            assignee_id      = assignee_id,
            org_id           = org_id,
            notes            = notes,
            due_at           = due_at,
        )
        self._assignments[assignment.assignment_id] = assignment
        key = (investigation_id, tenant_id)
        self._by_investigation.setdefault(key, []).append(assignment.assignment_id)
        log.info(
            "CollaborationTracker: investigation %s assigned to %s by %s",
            investigation_id[:8], assignee_id[:8], assigned_by[:8],
        )
        return assignment

    def accept(self, tenant_id: str, assignment_id: str) -> InvestigationAssignment:
        a = self._get_assignment(tenant_id, assignment_id)
        a.status      = AssignmentStatus.ACCEPTED
        a.accepted_at = datetime.now(tz=UTC)
        return a

    def start_work(self, tenant_id: str, assignment_id: str) -> InvestigationAssignment:
        a = self._get_assignment(tenant_id, assignment_id)
        a.status = AssignmentStatus.IN_REVIEW
        return a

    def complete_assignment(
        self,
        tenant_id:     str,
        assignment_id: str,
    ) -> InvestigationAssignment:
        a = self._get_assignment(tenant_id, assignment_id)
        a.status       = AssignmentStatus.COMPLETED
        a.completed_at = datetime.now(tz=UTC)
        return a

    def decline(
        self,
        tenant_id:     str,
        assignment_id: str,
        reason:        str = "",
    ) -> InvestigationAssignment:
        a = self._get_assignment(tenant_id, assignment_id)
        a.status = AssignmentStatus.DECLINED
        if reason:
            a.notes = f"Declined: {reason}"
        return a

    def reassign(
        self,
        tenant_id:      str,
        assignment_id:  str,
        new_assignee_id: str,
        reassigned_by:  str,
        notes:          str = "",
    ) -> InvestigationAssignment:
        old = self._get_assignment(tenant_id, assignment_id)
        old.status = AssignmentStatus.REASSIGNED

        new_assignment = InvestigationAssignment(
            assignment_id        = str(uuid.uuid4()),
            tenant_id            = tenant_id,
            investigation_id     = old.investigation_id,
            assigned_by          = reassigned_by,
            assignee_id          = new_assignee_id,
            org_id               = old.org_id,
            notes                = notes,
            due_at               = old.due_at,
            prior_assignment_id  = assignment_id,
        )
        self._assignments[new_assignment.assignment_id] = new_assignment
        key = (old.investigation_id, tenant_id)
        self._by_investigation.setdefault(key, []).append(new_assignment.assignment_id)
        return new_assignment

    def list_assignments(
        self,
        tenant_id:   str,
        assignee_id: str | None = None,
        status:      AssignmentStatus | None = None,
    ) -> list[InvestigationAssignment]:
        return [
            a for a in self._assignments.values()
            if a.tenant_id == tenant_id
            and (assignee_id is None or a.assignee_id == assignee_id)
            and (status is None or a.status == status)
        ]

    def assignments_for_investigation(
        self,
        tenant_id:        str,
        investigation_id: str,
    ) -> list[InvestigationAssignment]:
        ids = self._by_investigation.get((investigation_id, tenant_id), [])
        return [self._assignments[aid] for aid in ids if aid in self._assignments]

    # ── Review requests ────────────────────────────────────────────────────────

    def request_review(
        self,
        tenant_id:        str,
        investigation_id: str,
        requested_by:     str,
        reviewer_id:      str,
        reason:           str,
        priority:         str = "normal",
    ) -> ReviewRequest:
        review = ReviewRequest(
            review_id        = str(uuid.uuid4()),
            tenant_id        = tenant_id,
            investigation_id = investigation_id,
            requested_by     = requested_by,
            reviewer_id      = reviewer_id,
            reason           = reason,
            priority         = priority,
        )
        self._reviews[review.review_id] = review
        log.info(
            "CollaborationTracker: review requested for investigation %s → reviewer %s",
            investigation_id[:8], reviewer_id[:8],
        )
        return review

    def complete_review(
        self,
        tenant_id:     str,
        review_id:     str,
        reviewer_id:   str,
        outcome:       ReviewOutcome,
        outcome_notes: str = "",
    ) -> ReviewRequest:
        review = self._reviews.get(review_id)
        if review is None or review.tenant_id != tenant_id:
            raise CollaborationError(f"ReviewRequest {review_id} not found")
        if review.reviewer_id != reviewer_id:
            raise CollaborationError("Only the assigned reviewer may complete this review")

        review.status        = AssignmentStatus.COMPLETED
        review.outcome       = outcome
        review.outcome_notes = outcome_notes
        review.completed_at  = datetime.now(tz=UTC)
        return review

    def pending_reviews(
        self,
        tenant_id:   str,
        reviewer_id: str | None = None,
    ) -> list[ReviewRequest]:
        return [
            r for r in self._reviews.values()
            if r.tenant_id == tenant_id
            and r.status == AssignmentStatus.OPEN
            and (reviewer_id is None or r.reviewer_id == reviewer_id)
        ]

    # ── Overdue detection ──────────────────────────────────────────────────────

    def overdue_assignments(self, tenant_id: str) -> list[InvestigationAssignment]:
        return [
            a for a in self._assignments.values()
            if a.tenant_id == tenant_id and a.is_overdue
        ]

    # ── Helpers ────────────────────────────────────────────────────────────────

    def _get_assignment(
        self,
        tenant_id:     str,
        assignment_id: str,
    ) -> InvestigationAssignment:
        a = self._assignments.get(assignment_id)
        if a is None or a.tenant_id != tenant_id:
            raise CollaborationError(f"Assignment {assignment_id} not found")
        return a


# ── Exceptions ─────────────────────────────────────────────────────────────────

class CollaborationError(Exception):
    pass


# ── Singleton ──────────────────────────────────────────────────────────────────

_tracker: CollaborationTracker | None = None


def get_collaboration_tracker() -> CollaborationTracker:
    global _tracker
    if _tracker is None:
        _tracker = CollaborationTracker()
    return _tracker
