"""
Notification models for tenant-aware alert and event delivery.

Notifications are generated by platform events (escalations, review
requests, upgrade alerts, quota warnings) and delivered via the
NotificationDispatcher to the appropriate recipients.

Delivery channels
─────────────────
  IN_APP     — stored in platform; surfaced in UI notification centre
  EMAIL      — sent via the configured SMTP/SES integration
  WEBHOOK    — POSTed to a registered tenant webhook endpoint
  SLACK      — posted to a configured Slack channel (optional integration)
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any


class NotificationType(str, Enum):
    # Investigations
    INVESTIGATION_ASSIGNED    = "investigation_assigned"
    INVESTIGATION_ESCALATED   = "investigation_escalated"
    INVESTIGATION_RESOLVED    = "investigation_resolved"
    REVIEW_REQUESTED          = "review_requested"
    REVIEW_COMPLETED          = "review_completed"
    # Marketplace
    TEMPLATE_UPGRADE_AVAILABLE = "template_upgrade_available"
    TEMPLATE_APPROVED          = "template_approved"
    TEMPLATE_REJECTED          = "template_rejected"
    # Billing / quota
    QUOTA_WARNING             = "quota_warning"     # 80 % used
    QUOTA_CRITICAL            = "quota_critical"    # 95 % used
    BILLING_PERIOD_FINALISED  = "billing_period_finalised"
    # Governance / admin
    POLICY_OVERRIDE_EXPIRING  = "policy_override_expiring"
    RULE_PACK_UPDATED         = "rule_pack_updated"
    API_KEY_EXPIRING          = "api_key_expiring"
    TENANT_SUSPENSION_WARNING = "tenant_suspension_warning"
    # System
    SYSTEM_ALERT              = "system_alert"
    MAINTENANCE_WINDOW        = "maintenance_window"


class NotificationChannel(str, Enum):
    IN_APP  = "in_app"
    EMAIL   = "email"
    WEBHOOK = "webhook"
    SLACK   = "slack"


class NotificationPriority(str, Enum):
    LOW      = "low"
    NORMAL   = "normal"
    HIGH     = "high"
    CRITICAL = "critical"


class NotificationStatus(str, Enum):
    PENDING   = "pending"
    SENT      = "sent"
    READ      = "read"
    FAILED    = "failed"
    DISMISSED = "dismissed"


@dataclass
class Notification:
    """
    A single notification for a specific recipient within a tenant.

    Notifications are immutable once created — status transitions
    (PENDING→SENT, SENT→READ, etc.) are applied in-place.
    """
    notification_id: str
    tenant_id:       str
    recipient_id:    str                # user_id of the intended recipient
    notification_type: NotificationType
    title:           str
    body:            str
    priority:        NotificationPriority
    channel:         NotificationChannel
    status:          NotificationStatus = NotificationStatus.PENDING
    created_at:      datetime           = field(default_factory=lambda: datetime.now(tz=UTC))
    sent_at:         datetime | None = None
    read_at:         datetime | None = None
    expires_at:      datetime | None = None
    reference_id:    str | None      = None     # linked entity (investigation_id, template_id, …)
    reference_type:  str | None      = None     # "investigation" | "template" | "quota" | …
    metadata:        dict[str, Any]     = field(default_factory=dict)

    @property
    def is_expired(self) -> bool:
        if self.expires_at is None:
            return False
        return datetime.now(tz=UTC) > self.expires_at

    def mark_sent(self) -> None:
        self.status  = NotificationStatus.SENT
        self.sent_at = datetime.now(tz=UTC)

    def mark_read(self) -> None:
        self.status  = NotificationStatus.READ
        self.read_at = datetime.now(tz=UTC)

    def dismiss(self) -> None:
        self.status = NotificationStatus.DISMISSED

    def to_dict(self) -> dict[str, Any]:
        return {
            "notification_id":   self.notification_id,
            "tenant_id":         self.tenant_id,
            "recipient_id":      self.recipient_id,
            "notification_type": self.notification_type.value,
            "title":             self.title,
            "body":              self.body,
            "priority":          self.priority.value,
            "channel":           self.channel.value,
            "status":            self.status.value,
            "created_at":        self.created_at.isoformat(),
            "sent_at":           self.sent_at.isoformat() if self.sent_at else None,
            "read_at":           self.read_at.isoformat() if self.read_at else None,
            "reference_id":      self.reference_id,
            "reference_type":    self.reference_type,
        }


@dataclass
class NotificationPreference:
    """
    A user's per-type channel and quiet-hours preferences.

    If channels is empty, the user receives the platform default (IN_APP).
    Quiet-hours are stored as (start_hour, end_hour) in UTC (0–23).
    Only CRITICAL priority bypasses quiet hours.
    """
    preference_id:   str
    tenant_id:       str
    user_id:         str
    notification_type: NotificationType
    channels:        list[NotificationChannel] = field(default_factory=list)
    enabled:         bool                      = True
    quiet_start_utc: int | None             = None   # 0–23
    quiet_end_utc:   int | None             = None   # 0–23
    updated_at:      datetime = field(default_factory=lambda: datetime.now(tz=UTC))

    def effective_channels(self) -> list[NotificationChannel]:
        return self.channels or [NotificationChannel.IN_APP]

    def is_quiet_now(self, priority: NotificationPriority) -> bool:
        """Return True if delivery should be suppressed due to quiet hours."""
        if priority == NotificationPriority.CRITICAL:
            return False
        if self.quiet_start_utc is None or self.quiet_end_utc is None:
            return False
        hour = datetime.now(tz=UTC).hour
        s, e = self.quiet_start_utc, self.quiet_end_utc
        if s <= e:
            return s <= hour < e
        # Wraps midnight
        return hour >= s or hour < e

    def to_dict(self) -> dict[str, Any]:
        return {
            "preference_id":     self.preference_id,
            "tenant_id":         self.tenant_id,
            "user_id":           self.user_id,
            "notification_type": self.notification_type.value,
            "channels":          [c.value for c in self.channels],
            "enabled":           self.enabled,
            "quiet_start_utc":   self.quiet_start_utc,
            "quiet_end_utc":     self.quiet_end_utc,
        }


def new_notification_id() -> str:
    return f"ntf_{uuid.uuid4().hex[:16]}"
