"""
CorrelationReporter — renders cross-case correlation analysis into reports.

Accepts CorrelationReport from CorrelationEngine and produces structured
Markdown or JSON for investigator review and audit lineage.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from intelligence.services.correlation import CorrelationRecord, CorrelationReport


_STRENGTH_LABEL = {
    (0.80, 1.00): "Very High",
    (0.60, 0.80): "High",
    (0.40, 0.60): "Moderate",
    (0.00, 0.40): "Low",
}


def _strength_label(strength: float) -> str:
    for (lo, hi), label in _STRENGTH_LABEL.items():
        if lo <= strength < hi:
            return label
    return "Low"


class CorrelationReporter:

    def render_markdown(self, report: CorrelationReport) -> str:
        lines: list[str] = []

        lines += [
            "# Cross-Case Correlation Report",
            f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "---",
            "",
            "## Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Cases scanned               | {report.total_cases_scanned} |",
            f"| Total correlations detected | {report.total_correlations} |",
            f"| High-strength (≥ 0.6)       | {report.high_strength_count} |",
            f"| Shared pharmacy pairs       | {report.shared_pharmacy_count} |",
            f"| Shared NDC pairs            | {report.shared_ndc_count} |",
            f"| Multi-factor pairs          | {report.multi_factor_count} |",
            "",
        ]

        top = report.top_n(10)
        if top:
            lines += [
                "## Top 10 Correlations by Strength",
                "",
                "| Case A | Case B | Type | Strength | Label | Shared |",
                "|--------|--------|------|----------|-------|--------|",
            ]
            for r in top:
                shared_str = ", ".join(f"{k}={v}" for k, v in (r.shared_entities or {}).items())[:40]
                lines.append(
                    f"| `{r.case_id_a[:8]}` "
                    f"| `{r.case_id_b[:8]}` "
                    f"| {r.correlation_type} "
                    f"| {r.strength:.4f} "
                    f"| {_strength_label(r.strength)} "
                    f"| {shared_str or '—'} |"
                )
            lines.append("")

        if report.recurring_pharmacies:
            lines += [
                "## Recurring Pharmacies (≥ 2 cases)",
                "",
                "| Pharmacy | Cases | Case IDs |",
                "|----------|-------|----------|",
            ]
            for p in report.recurring_pharmacies[:20]:
                case_ids = ", ".join(c[:8] for c in p.get("case_ids", [])[:5])
                if len(p.get("case_ids", [])) > 5:
                    case_ids += "…"
                lines.append(
                    f"| {p.get('label', p['pharmacy_id'])[:30]} "
                    f"| {p['case_count']} "
                    f"| {case_ids} |"
                )
            lines.append("")

        if report.recurring_ndcs:
            lines += [
                "## Recurring NDCs (≥ 2 cases)",
                "",
                "| NDC | Label | Cases |",
                "|-----|-------|-------|",
            ]
            for n in report.recurring_ndcs[:20]:
                lines.append(
                    f"| `{n['ndc_11']}` "
                    f"| {n.get('label', n['ndc_11'])[:30]} "
                    f"| {n['case_count']} |"
                )
            lines.append("")

        if len(report.records) > 10:
            lines += [
                "## All Correlation Records",
                "",
                "| Case A | Case B | Type | Strength |",
                "|--------|--------|------|----------|",
            ]
            for r in report.records:
                lines.append(
                    f"| `{r.case_id_a[:8]}` "
                    f"| `{r.case_id_b[:8]}` "
                    f"| {r.correlation_type} "
                    f"| {r.strength:.4f} |"
                )
            lines.append("")

        lines += [
            "---",
            "*Report generated by EvidentRx Intelligence Layer — Cross-Case Correlation Engine*",
        ]
        return "\n".join(lines)

    def render_json(self, report: CorrelationReport) -> dict:
        return {
            "schema_version":       "1.0",
            "report_type":          "cross_case_correlation",
            "generated_at":         report.generated_at.isoformat(),
            "summary": {
                "total_cases_scanned":   report.total_cases_scanned,
                "total_correlations":    report.total_correlations,
                "high_strength_count":   report.high_strength_count,
                "shared_pharmacy_count": report.shared_pharmacy_count,
                "shared_ndc_count":      report.shared_ndc_count,
                "multi_factor_count":    report.multi_factor_count,
            },
            "top_correlations":     [_record_to_dict(r) for r in report.top_n(10)],
            "all_correlations":     [_record_to_dict(r) for r in report.records],
            "recurring_pharmacies": report.recurring_pharmacies,
            "recurring_ndcs":       report.recurring_ndcs,
        }

    def write(
        self,
        report: CorrelationReport,
        output_dir: str | Path,
        fmt: str = "markdown",
    ) -> Path:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        date_str = report.generated_at.strftime("%Y%m%d")
        stem = f"correlations_{date_str}"
        if fmt == "json":
            path = output_dir / f"{stem}.json"
            path.write_text(json.dumps(self.render_json(report), indent=2, default=str))
        else:
            path = output_dir / f"{stem}.md"
            path.write_text(self.render_markdown(report))
        return path


def _record_to_dict(r: CorrelationRecord) -> dict:
    return {
        "case_id_a":        r.case_id_a,
        "case_id_b":        r.case_id_b,
        "correlation_type": r.correlation_type,
        "strength":         r.strength,
        "strength_label":   _strength_label(r.strength),
        "shared_entities":  r.shared_entities,
        "explanation":      r.explanation,
    }
