"""
TrendReporter — renders compliance trend analysis into Markdown or JSON.

Accepts TrendSummary output from TrendAnalysisService and produces
structured reports suitable for audit logs and investigator briefings.
"""
from __future__ import annotations

import json
from datetime import date, datetime
from pathlib import Path
from typing import Optional

from intelligence.services.trend_analysis import TrendRecord, TrendSummary


class TrendReporter:

    def render_markdown(self, summary: TrendSummary) -> str:
        lines: list[str] = []

        lines += [
            f"# Compliance Trend Report — {summary.window_type.upper()} Window",
            f"**As of:** {summary.as_of}  |  **Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Entities analysed | {summary.total_entities} |",
            f"| Rule codes active  | {summary.total_rule_codes} |",
            f"| **Critical trend** | {summary.critical_count} |",
            f"| Worsening          | {summary.worsening_count} |",
            f"| Stable             | {summary.stable_count} |",
            f"| Improving          | {summary.improving_count} |",
            "",
        ]

        if summary.top_worsening:
            lines += [
                "## Top Worsening Entities",
                "",
                "| Entity | Rule | Direction | Velocity (/day) | Risk Score | Prior Count | Current Count |",
                "|--------|------|-----------|-----------------|------------|-------------|---------------|",
            ]
            for r in summary.top_worsening[:15]:
                dir_emoji = {"critical": "🔴", "worsening": "🟠", "stable": "🟡", "improving": "🟢"}.get(r.trend_direction, "")
                lines.append(
                    f"| {r.entity_id[:16]} | `{r.rule_code}` "
                    f"| {dir_emoji} {r.trend_direction} "
                    f"| {r.velocity:+.4f} "
                    f"| {r.risk_score:.2f} "
                    f"| {r.prior_period_count} "
                    f"| {r.finding_count} |"
                )
            lines.append("")

        lines += [
            "## All Trend Records",
            "",
            "| Entity | Rule | Direction | Count | Critical | High | Velocity | Acceleration | Exposure |",
            "|--------|------|-----------|-------|----------|------|----------|--------------|---------|",
        ]
        for r in summary.records:
            lines.append(
                f"| {r.entity_id[:16]} | `{r.rule_code}` "
                f"| {r.trend_direction} "
                f"| {r.finding_count} "
                f"| {r.critical_count} "
                f"| {r.high_count} "
                f"| {r.velocity:+.4f} "
                f"| {r.acceleration:+.4f} "
                f"| ${r.financial_exposure:,.0f} |"
            )

        lines += [
            "",
            "---",
            f"*Report generated by EvidentRx Intelligence Layer — {summary.window_type} rolling window*",
        ]
        return "\n".join(lines)

    def render_json(self, summary: TrendSummary) -> dict:
        return {
            "schema_version": "1.0",
            "report_type":    "compliance_trend",
            "generated_at":   datetime.utcnow().isoformat(),
            "as_of":          summary.as_of.isoformat(),
            "window_type":    summary.window_type,
            "totals": {
                "entities":        summary.total_entities,
                "rule_codes":      summary.total_rule_codes,
                "critical":        summary.critical_count,
                "worsening":       summary.worsening_count,
                "stable":          summary.stable_count,
                "improving":       summary.improving_count,
            },
            "top_worsening": [_record_to_dict(r) for r in summary.top_worsening],
            "all_records":   [_record_to_dict(r) for r in summary.records],
        }

    def write(
        self,
        summary: TrendSummary,
        output_dir: str | Path,
        fmt: str = "markdown",
    ) -> Path:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        stem = f"trend_{summary.window_type}_{summary.as_of}"
        if fmt == "json":
            path = output_dir / f"{stem}.json"
            path.write_text(json.dumps(self.render_json(summary), indent=2, default=str))
        else:
            path = output_dir / f"{stem}.md"
            path.write_text(self.render_markdown(summary))
        return path


def _record_to_dict(r: TrendRecord) -> dict:
    return {
        "entity_id":          r.entity_id,
        "entity_type":        r.entity_type,
        "rule_code":          r.rule_code,
        "window_type":        r.window_type,
        "window_start":       r.window_start.isoformat(),
        "window_end":         r.window_end.isoformat(),
        "finding_count":      r.finding_count,
        "critical_count":     r.critical_count,
        "high_count":         r.high_count,
        "financial_exposure": r.financial_exposure,
        "risk_score":         r.risk_score,
        "trend_direction":    r.trend_direction,
        "velocity":           r.velocity,
        "acceleration":       r.acceleration,
        "prior_period_count": r.prior_period_count,
    }
